version: '3.9'

services:

  fosscord:
    container_name: fosscord
    image: fosscord
    restart: on-failure:5
    build: .
    ports:
      - '3001-3001:3001-3001'
    volumes:
      - ./:/srv/fosscord-server/
    environment:
      THREADS: ${THREADS:-1}
      HTTP_PORT: 3001
      WS_PORT: 3001
      CDN_PORT: 3001
      RTC_PORT: 3001
      ADMIN_PORT: 3001

networks:
  default:
    name: fosscord
    driver: bridge
